# services lists the multiple different apps we want to run via docker
services:
  # name for the service
  api:
    # location of the Dockerfile
    build: ./server
    depends_on:
      db:
        condition: service_healthy
    # ports
    ports:
      - 3000:3000

  # name for second service
  client:
    # dockerfile can be in different directory
    build: ./client
    # runs on a different port from first app
    ports:
      - 1234:1234

  # name for database service
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes: 
      - ~/apps/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: business_contacts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_INITDB_SCRIPT: init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 3